Implement AsyncRead and AsyncWrite for TcpStream
second-state/wasmedge_wasi_socket pull request #52
Opened 2022-05-14 04:39 UTC by MediosZ

This PR implements AsyncRead and AsyncWrite for TcpStream.
Related to [Async Runtime.](https://github.com/WasmEdge/WasmEdge/issues/1429)
Signed-off-by: Tricster <mediosrity@qq.com>

2022-05-14 17:14 UTC, hydai requested changes
Please check the CI failed messages.

2022-05-14 17:14 UTC, hydai commented on src/lib.rs
> +            // match std::io::Read::read(this, b) {
Do we need this comment?

2022-05-15 01:07 UTC, MediosZ commented on src/lib.rs
> +            // match std::io::Read::read(this, b) {
Sorry I forgot to delete it.

2022-05-17 03:19 UTC, hydai commented
Hi @MediosZ 
I will do the review by Wednesday.

2022-05-18 05:03 UTC, hydai approved these changes

2022-05-18 05:04 UTC, merged